import test from 'node:test';import assert from 'node:assert/strict';import {resizeCanvas} from '../dist/canvas-size.js';
function fixture(){let width=300,height=150,writes=0;const canvas={clientWidth:390,clientHeight:505,get width(){return width},set width(v){width=v;writes++},get height(){return height},set height(v){height=v;writes++}};const transforms=[],context={setTransform:(...x)=>transforms.push(x)};return {canvas,context,transforms,writes:()=>writes};}
test('duplicate resize notifications do not reallocate the canvas',()=>{const f=fixture();assert.equal(resizeCanvas(f.canvas,f.context,1.5),true);assert.equal(f.canvas.width,585);assert.equal(f.canvas.height,757);for(let i=0;i<50;i++)assert.equal(resizeCanvas(f.canvas,f.context,1.5),false);assert.equal(f.writes(),2);assert.deepEqual(f.transforms.at(-1),[1.5,0,0,1.5,0,0]);});
test('actual viewport changes update only changed dimensions and cap pixel density',()=>{const f=fixture();resizeCanvas(f.canvas,f.context,1);f.canvas.clientWidth=430;resizeCanvas(f.canvas,f.context,1);assert.equal(f.writes(),3);assert.equal(f.canvas.width,430);resizeCanvas(f.canvas,f.context,3);assert.equal(f.canvas.width,860);assert.equal(f.canvas.height,1010);});
test('zero-size or invalid ratios stay finite and cannot create a negative buffer',()=>{const f=fixture();f.canvas.clientWidth=0;f.canvas.clientHeight=0;resizeCanvas(f.canvas,f.context,NaN);assert.equal(f.canvas.width,1);assert.equal(f.canvas.height,1);assert.deepEqual(f.transforms.at(-1),[1,0,0,1,0,0]);});
test('rapid orientation changes and narrow restores keep exact logical scaling',()=>{
 const f=fixture();const sizes=[[390,505,1.5],[844,362,1.5],[390,505,1.5],[500,757,1],[1100,757,1],[500,757,1],[390,505,1.5]];
 for(const [w,h,d] of sizes){f.canvas.clientWidth=w;f.canvas.clientHeight=h;resizeCanvas(f.canvas,f.context,d);const writes=f.writes();for(let n=0;n<10;n++)resizeCanvas(f.canvas,f.context,d);assert.equal(f.writes(),writes);assert.equal(f.canvas.width,Math.floor(w*d));assert.equal(f.canvas.height,Math.floor(h*d));assert.deepEqual(f.transforms.at(-1),[d,0,0,d,0,0]);}
 assert.equal(f.canvas.width,585);assert.equal(f.canvas.height,757);assert.ok(f.writes()<=sizes.length*2);
});
