import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {Judge,pointAt,calibration} from '../dist/engine.js';import {Music} from '../dist/music.js';
const chart=JSON.parse(fs.readFileSync(new URL('../dist/chart.json',import.meta.url))),notes=chart.notes;
test('117 nodes, 32 bars, 64 seconds and proportional unique route',()=>{assert.equal(notes.length,117);assert.equal(chart.barPatternSequence.length,32);assert.equal(chart.durationBeats/2,64);for(let i=0;i<notes.length;i++){let a=notes[i],b=notes[i+1]||chart.terminal;assert.ok(b.beat>a.beat);assert.ok(b.beat-a.beat>=.5);assert.ok(Number.isInteger(a.beat*2));assert.ok(b.position[0]>a.position[0]);assert.ok(Math.abs(Math.hypot(...b.position.map((v,j)=>v-a.position[j]))-(b.beat-a.beat)*48)<.001);if(notes[i+1])assert.notEqual(a.outgoingAngleScreenDegrees,b.outgoingAngleScreenDegrees);}});
test('inclusive perfect and good boundaries, both signs',()=>{for(const d of [-.09,-.04,.04,.09]){let j=new Judge(notes);assert.equal(j.press(d).kind,Math.abs(d)<=.04?'perfect':'good');}assert.equal(new Judge(notes).press(-.0901).kind,'stray');});
test('offset sign applied once',()=>{assert.equal(new Judge(notes,0,128,.06).press(.06).kind,'perfect');assert.equal(new Judge(notes,0,128,-.06).press(-.06).kind,'perfect');});
test('early judgments do not move geometry; late correction remains valid',()=>{const p=pointAt(notes,chart.terminal,-.1),j=new Judge(notes);j.press(-.04);assert.deepEqual(pointAt(notes,chart.terminal,-.1),p);const k=new Judge(notes);k.expire(.089);assert.equal(k.press(.09).kind,'good');k.expire(.1);assert.equal(k.stats().miss,0);});
test('one note settles once, strays break combo but preserve future notes',()=>{const j=new Judge(notes);j.press(0);j.press(.01);assert.equal(j.stats().hits,1);assert.equal(j.combo,0);assert.equal(j.strays,1);j.press(.5);assert.equal(j.stats().hits,2);});
test('misses and final flush; zero inputs cannot full combo',()=>{const j=new Judge(notes);j.expire(65);assert.equal(j.stats().miss,117);assert.equal(j.stats().fullCombo,false);j.expire(70);assert.equal(j.stats().miss,117);});
test('replay deterministic and independent from 30/60/144Hz frame queries',()=>{const results=[];for(const fps of [30,60,144]){const j=new Judge(notes);let t=-2;for(const n of notes){while(t<n.beat/2){pointAt(notes,chart.terminal,t*2);t+=1/fps;}j.press(n.beat/2);}j.expire(65);results.push(j.stats());}assert.deepEqual(results[0],results[1]);assert.deepEqual(results[1],results[2]);assert.equal(results[0].fullCombo,true);assert.equal(results[0].score,117000);});
test('rollback removes repeated bar and rebuilds combos; reset clears everything',()=>{const j=new Judge(notes);for(let b=0;b<8;b++)j.press(b/2);j.rollback(4);assert.equal(j.stats().hits,4);assert.equal(j.maxCombo,4);for(let b=4;b<8;b++)j.press(b/2);assert.equal(j.stats().hits,8);j.reset();assert.equal(j.stats().hits,0);assert.equal(j.maxCombo,0);});
test('practice has separate totals and subset',()=>{const j=new Judge(notes,32,64);assert.equal(j.notes.length,25);for(const n of j.notes)j.press(n.beat/2);assert.equal(j.stats().fullCombo,true);});
test('calibration median, minimum samples, jitter rejection',()=>{assert.equal(calibration([.05]),null);assert.equal(calibration(Array(16).fill(.06)).offset,60);assert.equal(calibration(Array.from({length:16},(_,i)=>i%2?.18:-.18)).stable,false);assert.equal(calibration(Array(16).fill(-.06)).offset,-60);});
class Param{value=0;setValueAtTime(){}exponentialRampToValueAtTime(){}}class FakeNode{gain=new Param();frequency=new Param();connect(){}disconnect(){}start(t){assert.ok(Number.isFinite(t));}stop(){}}
test('original song scheduling matches every chart lead and deterministic counts; stop resets sources',()=>{const ctx={sampleRate:100,currentTime:0,destination:{},createGain:()=>new FakeNode(),createBuffer:(_,n)=>({getChannelData:()=>new Float32Array(n)}),createOscillator:()=>new FakeNode(),createBufferSource:()=>new FakeNode(),createBiquadFilter:()=>new FakeNode()};const m=new Music(ctx),calls=[];m.tone=(...a)=>calls.push(a);m.hat=()=>{};m.schedule(notes,2,0,128);assert.equal(calls.filter(x=>x[3]===.095).length,117);assert.deepEqual(calls.filter(x=>x[3]===.095).map(x=>x[0]),notes.map(n=>2+n.beat/2));const first=JSON.stringify(calls);calls.length=0;m.schedule(notes,2,0,128);assert.equal(JSON.stringify(calls),first);m.stop();assert.equal(m.nodes.length,0);});
